#ifndef _SETTINGS_HPP_
#define _SETTINGS_HPP_

#define GAME_WIDTH 130
#define GAME_HEIGHT 38

#define TICK_INTERVAL 0.075f

#define PLAYER_STARTING_HEALTH 50
#define PLAYER_MAX_HEALTH 100
#define PLAYER_MAX_COINS 999

#define ENEMY_STARTING_HEALTH 10

#define RIGIDBODY_STARTING_VEL_X 0
#define RIGIDBODY_STARTING_VEL_Y 0

#define MAX_ABS_X_VEL 7
#define MAX_JUMP_VEL 4
#define MAX_FALL_VEL -2

#define QUIT_KEY 'q'

#define PLAYER_NAME "GAETANO"

#define PLAYER_JUMP_VEL 3
#define PLAYER_WALK_VEL 2
#define PLAYER_RUN_VEL 3

#define ENEMY_VEL 1
#define PROJECTILE_VEL 3

#define ENEMY_DAMAGE 10

#define HEART_HEALTH_INCREASE 30

#define PLAYER_RENDER_CHARACTER "@"
#define PLAYER_POWERUP_RENDER_CHARACTER "&"
#define PLAYER_GUN_RENDER_CHARACTER "@"
#define ENEMY_RENDER_CHARACTER "E"
#define POWERUP_RENDER_DISABLED_CHARACTER "X"

#define MIN_NUMBER_OF_COINS 2
#define COINS_RENDER_DIGITS 3

#define PLAYER_DAMAGED_TOTAL_TICKS 8
#define PLAYER_DAMAGED_BLINK_TICKS 2

#define PLAYER_START_POS_OFFSET 5
#define ENEMY_DISTANCE_FROM_START 20
#define POWERUP_DISTANCE_FROM_START 10

#define STAR_POWERUP_DURATION_SECONDS 10
#define PROJECTILE_DELAY_MS 300
#define PROJECTILE_RENDER_CHARACTER "-"

#define ENEMY_SHOOTING_MIN_DIFFICULTY 5

#define ENEMY_SHOOTING_MIN_DELAY_SEC 1
#define ENEMY_SHOOTING_MAX_DELAY_SEC 10

#define PROJECTILE_DAMAGE 10

#define STARTING_DIFFICULTY 1

enum class EntityType {
    StaticEntity,
    RigidEntity,
    Powerup,
    Mushroom,
    Star,
    Heart,
    Coin,
    Gun,
    Player,
    Enemy,
};

enum class Direction {
    Left,
    Right,
};

#endif  // _SETTINGS_HPP_