#ifndef _SETTINGS_HPP_
#define _SETTINGS_HPP_

#define GAME_WIDTH 130
#define GAME_HEIGHT 38

#define TICK_INTERVAL 0.069f

#define PLAYER_STARTING_HEALTH 100
#define PLAYER_MAX_HEALTH 100

#define RIGIDBODY_STARTING_VEL_X 0
#define RIGIDBODY_STARTING_VEL_Y 0

#define MAX_ABS_X_VEL 7
#define MAX_ABS_Y_VEL 3

#define QUIT_KEY 'q'

#define PLAYER_JUMP_VEL 2
#define PLAYER_RENDER_CHARACTER "@"

#endif  // _SETTINGS_HPP_